import {
  Activity,
  ArrowLeftRight,
  BadgeCheck,
  Ban,
  BookOpen,
  Boxes,
  Camera,
  CircleCheck,
  Clock,
  Code,
  Cpu,
  Database,
  Download,
  Eye,
  FileCheck,
  FileText,
  Film,
  Fingerprint,
  GitBranch,
  Globe,
  Home,
  HardDrive,
  KeyRound,
  Laptop,
  Layers,
  ListChecks,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Milestone,
  Monitor,
  Network,
  Newspaper,
  Package,
  Palette,
  PenTool,
  Radio,
  RefreshCw,
  Rocket,
  Scale,
  Server,
  Share2,
  ShieldCheck,
  Sparkles,
  SquareTerminal,
  Timer,
  User,
  Users,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Icons are referenced by key so page content stays plain, serialisable data.
export const ICONS = {
  activity: Activity,
  transfer: ArrowLeftRight,
  badge: BadgeCheck,
  ban: Ban,
  book: BookOpen,
  boxes: Boxes,
  camera: Camera,
  check: CircleCheck,
  clock: Clock,
  code: Code,
  cpu: Cpu,
  database: Database,
  download: Download,
  eye: Eye,
  filecheck: FileCheck,
  file: FileText,
  film: Film,
  fingerprint: Fingerprint,
  git: GitBranch,
  globe: Globe,
  home: Home,
  drive: HardDrive,
  key: KeyRound,
  laptop: Laptop,
  layers: Layers,
  list: ListChecks,
  lock: Lock,
  mail: Mail,
  map: Map,
  message: MessageSquare,
  milestone: Milestone,
  monitor: Monitor,
  network: Network,
  news: Newspaper,
  package: Package,
  palette: Palette,
  pen: PenTool,
  radio: Radio,
  refresh: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  server: Server,
  share: Share2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: SquareTerminal,
  timer: Timer,
  user: User,
  users: Users,
  wifi: Wifi,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;
